name: Test The Docker Build
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Ruby-Network'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Submodule Update
        run: git submodule update --init --recursive
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Build
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: ruby-network/ruby-network:testing
